name: Build and deploy Gatsby site.
on: [push]
jobs:
  Build-Deploy-Gatsby-Site:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: checkout main branch into main folder.
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: remove all files
        run: rm -rf main/*
      - name: create CNAME file
        run: echo "bytemaya.com" > main/CNAME

      - name: checkout master branch into master folder.
        uses: actions/checkout@v2
        with:
          ref: master
          path: master

      - name: run yarn install and build
        run: |
          cd master
          yarn install
          yarn build

      - name: move files
        if: ${{ success() }}
        run: |
          mv master/public/* main/.
          rm -rf master

      - name: Commit files for change
        if: ${{ success() }}
        run: |
          cd main
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes"

      - name: Push changes
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          BRANCH: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          directory: main

      
